title: Yasemin Karaca
#logo: /assets/img/
contact: Bournemouth/England <br/> yaseminxkaraca@gmail.com <br/>
#description: Highly motivated computer engineering graduate with a strong foundation in programming and systems design, currently pursuing an MSc. in Data Science and Artificial Intelligence. I bring a structured, energetic, collaborative work style with excellent communication skills to improve and optimise processes. I possess strong critical thinking, problem-solving, and time management skills, allowing me to effectively utilise my technical expertise for a career in AI development and application. My aim is to bridge the gap between theoretical knowledge and practical work-life skills.
#show_downloads: true
description: Contact: <br/> Bournemouth/England <br/> yaseminkaraca@gmail.com <br/>
skills: C++, Java, Python, SQL, Swift, MATLAB, MIPS, Verilog, Word, Excel, PowerPoint, DataPreprocessing, Data Visualisation, Computer Vision
languages: Turkish (Native), English (Fluent), French(Basic Knowledge)
theme: jekyll-theme-minimal
