title: Yasemin Karaca
#logo: /assets/img/headshot_circle.png
#description: text below image
#contact: Bournemouth/England <br/> yaseminxkaraca@gmail.com <br/>
description: <b> Contact: </b> <br/> Bournemouth/England <br/> yaseminxkaraca@gmail.com <br/>
#show_downloads: true
theme: jekyll-theme-minimal
